repos:
  - repo: local
    hooks:
      - id: frontend-biome-check
        name: Frontend Biome Check
        entry: bash -c "cd frontend && pnpm check"
        language: system
        types: [file]
        files: ^frontend/
        pass_filenames: false
        
      - id: backend-ty-and-ruff-check
        name: Backend Ty and Ruff Check
        entry: bash -c "cd backend && uv run ruff check && uv run ty check"
        language: system
        types: [file]
        files: ^backend/
        pass_filenames: false
