/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Root */
		get: operations["root__get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/gemini": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Make Gemini Response */
		get: operations["make_gemini_response_gemini_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/exercises": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Exercises
		 * @description 種目一覧の取得
		 */
		get: operations["get_exercises_exercises_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sessions": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Sessions
		 * @description 記録一覧の取得(WorkoutSessionに紐づくdetailsと、そのexercise情報もネストして返す)
		 */
		get: operations["get_sessions_sessions_get"];
		put?: never;
		/**
		 * Create Session
		 * @description 日々の記録の登録(WorkoutSessionを先に作成し、紐づくWorkoutDetailを保存)
		 */
		post: operations["create_session_sessions_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/suggest": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Suggest
		 * @description コンディションと運動可能時間をもとに今日のメニューを提案
		 */
		post: operations["suggest_suggest_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * Exercise
		 * @description 固定種目データ
		 */
		Exercise: {
			/** Id */
			id: number;
			/** Name */
			name: string;
			/**
			 * Training Type
			 * @enum {string}
			 */
			training_type: "aerobic" | "anaerobic";
			/** Target Muscles */
			target_muscles: string[];
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components["schemas"]["ValidationError"][];
		};
		/**
		 * SuggestRequest
		 * @description メニュー提案リクエスト
		 */
		SuggestRequest: {
			/** Condition */
			condition: number;
			/** Available Hours */
			available_hours: number;
		};
		/**
		 * SuggestResponse
		 * @description Geminiによるメニュー提案レスポンス
		 */
		SuggestResponse: {
			/** Reasoning */
			reasoning: string;
			/** Exercises */
			exercises: components["schemas"]["SuggestedExercise"][];
			/** Estimated Duration */
			estimated_duration: number;
		};
		/**
		 * SuggestedExercise
		 * @description Geminiが提案する1種目
		 */
		SuggestedExercise: {
			/** Exercise Id */
			exercise_id: number;
			/** Name */
			name: string;
			/** Training Type */
			training_type: "aerobic" | "anaerobic";
			/**
			 * Sets
			 * @description セット数（1以上）。有酸素種目は1
			 */
			sets: number;
			/**
			 * Reps
			 * @description 有酸素種目は運動時間(分)、無酸素種目は1セットあたりの回数
			 */
			reps: number;
			/**
			 * Weight
			 * @description 使用重量(kg)。有酸素種目は0。無酸素種目は履歴を参考に設定し、履歴がなければ初心者レベルの値（例: チェストプレス=30、ラットプルダウン=30、レッグプレス=40）を必ず設定すること。0にしてはいけない。
			 */
			weight: number;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
		/**
		 * WorkoutDetailCreate
		 * @description 詳細記録作成用スキーマ
		 */
		WorkoutDetailCreate: {
			/** Exercise Id */
			exercise_id: number;
			/** Weight */
			weight: number;
			/** Reps */
			reps: number;
			/**
			 * Sets
			 * @default 1
			 */
			sets: number;
		};
		/**
		 * WorkoutDetailRead
		 * @description 詳細記録読み取り用スキーマ(Exercise情報を含む)
		 */
		WorkoutDetailRead: {
			/** Id */
			id: number;
			/** Exercise Id */
			exercise_id: number;
			/** Weight */
			weight: number;
			/** Reps */
			reps: number;
			/** Sets */
			sets: number;
			exercise: components["schemas"]["Exercise"];
		};
		/**
		 * WorkoutSession
		 * @description 日々の記録
		 */
		WorkoutSession: {
			/** Id */
			id?: number | null;
			/**
			 * Session Date
			 * Format: date
			 */
			session_date: string;
			/** Condition */
			condition: number;
		};
		/**
		 * WorkoutSessionCreate
		 * @description セッション作成用スキーマ(詳細レコードを含む)
		 */
		WorkoutSessionCreate: {
			/**
			 * Session Date
			 * Format: date
			 */
			session_date: string;
			/**
			 * Condition
			 * @default 3
			 */
			condition: number;
			/** Details */
			details: components["schemas"]["WorkoutDetailCreate"][];
		};
		/**
		 * WorkoutSessionRead
		 * @description セッション読み取り用スキーマ(詳細レコードを含む)
		 */
		WorkoutSessionRead: {
			/** Id */
			id: number;
			/**
			 * Session Date
			 * Format: date
			 */
			session_date: string;
			/** Condition */
			condition: number;
			/** Details */
			details: components["schemas"]["WorkoutDetailRead"][];
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	root__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
		};
	};
	make_gemini_response_gemini_get: {
		parameters: {
			query: {
				input: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_exercises_exercises_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Exercise"][];
				};
			};
		};
	};
	get_sessions_sessions_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WorkoutSessionRead"][];
				};
			};
		};
	};
	create_session_sessions_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["WorkoutSessionCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["WorkoutSession"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	suggest_suggest_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SuggestRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SuggestResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
}
